### ISSUE TITLE
Realsense2 device is found, but cannot run program

### ISSUE THREAD

**Issue by hyeonjang** [bytedeco/procamcalib#26]
OS: ubuntu 20.04
Camera: Realsense2 D435i, L515

Hello,
When I tried to run this program, I encounter this message.

![image](https://user-images.githubusercontent.com/59863036/153557351-b936e7ed-a622-41cc-9988-b87f3cbf5f21.png)

Also, on a console the message indicates 
`
Realsense2 devices found: 1
`

I cannot figure out where this problem occurs.

Could you help  me?
Thanks

**Comment by saudet** [comment]
@cansik Any ideas?

**Comment by cansik** [comment]
For the `RealSense2FrameGrabber` it is necessary to first enable the necessary streams. Here an example ([samples/RealSense2DepthMeasuring.java#L44-L59](https://github.com/bytedeco/javacv/blob/master/samples/RealSense2DepthMeasuring.java#L44-L59)):

```java
// enable the color & depth stream of the realsense camera
rs2.enableColorStream(640, 480, 30);
rs2.enableDepthStream(640, 480, 30);

rs2.start();
```

I assume `procamcalib` needs the `start` method to directly enable at least the color input. In my opinion this should be included into the `RealSense2FrameGrabber`, if no stream has been activated, instead of the exception. It is possible to activate de default color stream by just passing `0` as parameter for width, height and framerate. Especially on the 515 camera this could be important, because there we have different resolutions and stream formats than on the 400 series.

@saudet Do you think this is a good default behaviour? If so I will create a PR.

**Comment by saudet** [comment]
That sounds like a good idea, yes. The default imageWidth, imageHeight, and frameRate should be taken from the properties though: https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FrameGrabber.java#L183

**Comment by saudet** [comment]
Thanks @cansik for fixing this! @hyeonjang please give it a try by replacing `modules/javacv.jar` with this file: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.5.8-SNAPSHOT/javacv-1.5.8-20220215.010447-6.jar

**Comment by hyeonjang** [comment]
@saudet @cansik Really thank you for updating! Now it works.
